name: pika_pika_test_project
description: A test project for Innowise inc.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-182.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  animations: ^2.0.2
  connectivity_plus: ^2.3.7
  get_it: ^7.2.0
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  stream_transform: ^2.0.0
  flutter_bloc: ^8.1.1
  get: ^4.6.5
  sqflite: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

